### ISSUE TITLE
Make end to end tests work on CI (ubuntu)

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/instant-meilisearch#294]
As for now we are using angular built-in protector/jasmine/Selenium stack to tests if the playground of angular generated the correct elements with instant-meilisearch.

Unfortunately, these tests are not possible on ubuntu-latest as ChromeDriver is not installed. 
We should find a solution to make the CI compatible with this tests as it ensures the most the working state of instant-meilisearch 

```
[16:45:56] I/launcher - Running 1 instances of WebDriver
[16:45:56] I/direct - Using ChromeDriver directly...
[16:46:01] E/runner - Unable to start a WebDriver session.
[16:46:01] E/launcher - Error: WebDriverError: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=88.0.4324.96 (68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}),platform=Linux 5.4.0-1039-azure x86_64)
    at Object.checkLegacyResponse (/home/runner/work/instant-meilisearch/instant-meilisearch/playgrounds/angular/node_modules/selenium-webdriver/lib/error.js:546:15)
    at parseHttpResponse (/home/runner/work/instant-meilisearch/instant-meilisearch/playgrounds/angular/node_modules/selenium-webdriver/lib/http.js:509:13)
    at /home/runner/work/instant-meilisearch/instant-meilisearch/playgrounds/angular/node_modules/selenium-webdriver/lib/http.js:441:30
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[16:46:01] E/launcher - Process exited with error code 100
```

see https://github.com/meilisearch/instant-meilisearch/pull/293/checks?check_run_id=1963073082

**Comment by bidoubiwa** [comment]
fixed by:  #409
